const BRAND_ALIASES: Record<string, string> = {
  "טויוטה": "Toyota",
  "יונדאי": "Hyundai",
  "צ'רי": "Chery",
  "צ׳רי": "Chery",
  "קיה": "Kia",
  "סקודה": "Skoda",
  "ג'אקו": "Jaecoo",
  "ג׳אקו": "Jaecoo",
  "BYD": "BYD",
  "MG": "MG",
  "מאזדה": "Mazda",
  "סיאט": "SEAT",
  "ניסאן": "Nissan",
  "מיצובישי": "Mitsubishi",
  "אקספנג": "XPeng",
  "XPENG": "XPeng",
  "טסלה": "Tesla",
  "סוזוקי": "Suzuki",
  "סיטרואן": "Citroen",
  "רנו": "Renault",
  "סובארו": "Subaru",
  "ג'ילי": "Geely",
  "ג׳ילי": "Geely",
  "פולקסווגן": "Volkswagen",
  "לינק אנד קו": "Lynk & Co",
  "לינקקו": "Lynk & Co",
  "לינקקו ": "Lynk & Co",
  "פיז'ו": "Peugeot",
  "פיג'ו": "Peugeot",
  "ב.מ.וו": "BMW",
  "לקסוס": "Lexus",
  "דונגפנג": "Dongfeng",
  "דאצ'יה": "Dacia",
  "דיפאל": "Deepal",
  "דיפל": "Deepal",
  "אאודי": "Audi",
  "זיקר": "Zeekr",
  "KGM": "KGM",
  "מקסוס": "Maxus",
  "וולוו": "Volvo",
  "SERES": "Seres",
  "סרס": "Seres",
  "קופרה": "Cupra",
  "מרצדס": "Mercedes-Benz",
  "מרצדס בנץ": "Mercedes-Benz",
  "מרצדס_בנץ": "Mercedes-Benz",
  "אופל": "Opel",
  "איסוזו": "Isuzu",
  "ליפמוטור": "Leapmotor",
  "שברולט": "Chevrolet",
  "סמארט": "smart",
  "הונגצ'י": "Hongqi",
  "הונגצ׳י": "Hongqi",
  "פורת'ינג": "Forthing",
  "פורטינג": "Forthing",
  "פורד": "Ford",
  "ג'יפ": "Jeep",
  "ג׳יפ": "Jeep",
  "JAC": "JAC",
  "לנד רובר": "Land Rover",
  "פיאט": "Fiat",
  "וויה": "Voyah",
  "ווייה": "Voyah",
  "וויוה": "Voyah",
  "סקייוול": "Skywell",
  "הונדה": "Honda",
  "ג'נסיס": "Genesis",
  "גניסיס": "Genesis",
  "מיני": "Mini",
  "פוטון": "Foton",
  "אלפא רומיאו": "Alfa Romeo",
  "אורה": "Ora",
  "NIO": "NIO",
  "GAC": "GAC",
  "פורשה": "Porsche",
  "אוואטר": "Avatr",
  "קאדילק": "Cadillac",
  "קדילאק": "Cadillac",
  "באיק": "BAIC",
  "BIAC": "BAIC",
  "Yudo": "Yudo",
  "יודו": "Yudo",
  "אבארט": "Abarth",
  "אברט": "Abarth",
  "בנטלי": "Bentley",
  "נטה": "NETA",
  "NETA": "NETA",
  "IM": "IM Motors",
  "IM מוטורס": "IM Motors",
  "IM_Motors": "IM Motors",
  "וויי": "WEY",
  "WEY": "WEY",
  "פרארי": "Ferrari",
  "SWM": "SWM",
  "אינפיניטי": "Infiniti",
  "אסטון מרטין": "Aston Martin",
  "אלפין": "Alpine",
  "DS": "DS",
  "DS אוטומובילס": "DS",
  "מזראטי": "Maserati",
};

export function toCanonicalBrandName(value: string) {
  const cleaned = value.replace(/\s+/g, " ").trim();
  return BRAND_ALIASES[cleaned] ?? cleaned;
}
